# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: false

- script: dotnet publish -o "_output" "Booking.Server/Booking.Server.API/Booking.Server.API.csproj"
  displayName: Dotnet Publish

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: 'Docker HUB'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker HUB'
    repository: 'damwar/booking-api'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
