# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

container: damwar/dotnet-sdk:latest

variables:
  publishPath:  '_output'
  testPath: '_testResults'

steps:
- script: dotnet test Booking.Server/ --logger trx --results-directory "$(testPath)"
  displayName: Dotnet Test

- script: dotnet publish -o "$(publishPath)" "Booking.Server/Booking.Server.API/Booking.Server.API.csproj"
  displayName: Dotnet Publish

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '$(testPath)/*.trx'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(publishPath)' 
    artifactName: 'dotnetPublish'