name: Docker Image CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Build-push-docker:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: 6.0.x
        - name: Publish API (with DB)
          run: dotnet publish -o "Booking.Server/_output" "Booking.Server/Booking.Server.API/Booking.Server.API.csproj"
        
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            push: true
            tags: damwar/booking-api:latest
