name: Docker Image CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Build-push-docker-from-artifact:

    runs-on: ubuntu-latest

    steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Download publish artifact
          uses: Legit-Labs/action-download-artifact@v2.18.0
          with:
            github_token: ${{ secrets.REPO_TOKEN }}
            workflow: .github/workflows/publish-and-test.yml
            path: /publish-artifact
        - name: Build and push
          uses: docker/build-push-action@v3.1.1
          with:
            push: true
            tags: damwar/booking-api:latest
